### ISSUE TITLE
Issue with library : values from sensors don't change

### ISSUE THREAD

**Issue by Julien-Dr** [alextaujenis/RBD_Capacitance#2]
Hi Alex,

First of all i want to thank you to make these arduino's libraries (human sensor, capacitance,…) that truely simplify the use of diy capacitive sensor. 

when i upload sketch to arduino board and i open monitor window, i can read values  (7) but they don't change (if i touch or not the aluminium foil).

i checked the circuit (resistor, foil, wires…). i tried with another arduino board, but values doesn't change in the monitor window.

I use arduino IDE 1.8.2 (i tried 1.6.2 too), arduino uno board vid : 2A03.

Do you have any suggestions to make it work ?

**Comment by alextaujenis** [comment]
Hi @Julien-Dr,

I don't have much information to work from here. All I can say is that I just tested this library (example code and wiring diagram) with an Arduino Micro as part of a small STEM project and everything works as expected. Try re-wiring your board again and make sure to follow the example wiring diagram.
